### PR TITLE
[vergo:minor-release] Look for head commit at any point of versioned branch

### LINKED ISSUE #13: Unable to bump version on older commits of versioned branches
When running `vergo bump minor` on a commit that's not the latest on a versioned branch, the command fails with `Error: HEAD validation: invalid headless checkout`.

E.g. if we have the git history for the master branch with `49aded0` being the latest commit:
```
* 49aded0 - [vergo:minor-release] Fix bug in tag prefix trimming (#12) (5 weeks ago)
* 9d2e3f5 - [vergo:minor-release] add bin to gitignore for goreleaser (#11) (6 weeks ago)
* fc783c0 - [vergo:minor-release] update contributing for release of stricthostchecking flag (#10) (6 weeks ago)
```
And I run `vergo bump minor` against the `9d2e3f5` it fails.

I believe it's because of this check https://github.com/sky-uk/vergo/blob/49aded085828ccbf9555f83473b207f59d86767c/release/release.go#L105 which was added by https://github.com/sky-uk/vergo/commit/b4527892b2f2206908dd3e5b4ba9fe3fb5d91b93. 

It looks like this check is to ensure vergo bump is only run on a versioned branch. However, it's only checking the current commit against the latest commit on the primary branch, not all commits.

### PR DESCRIPTION
**Pull request by adamdougal**
- This is an attempt to fix #13, using code shamelessly stolen from https://github.com/src-d/go-git/issues/611#issuecomment-334476754
- This allows vergo to release on older commits that live on the versioned branches e.g. `master` and `main` (by default)

Required by #13

### CODE REVIEW

**Comment by adamdougal** [comment]
Test output:

```bash
14:58:25 [~/workspace/vergo] {0}:gmake test
[[ `(gofmt -l .)`x == x ]] || (echo "go fmt failed" && gofmt -l . && exit 1)
go vet ./...
golangci-lint run ./...
BUILT_BY="`goreleaser --version | head -n1`, `go version`" \
GORELEASER_CURRENT_TAG=0+`git rev-parse --short HEAD` \
goreleaser build --snapshot --rm-dist
dist/vergo_`uname | tr A-Z a-z`_amd64/vergo version
cp dist/vergo_`uname | tr A-Z a-z`_amd64/vergo bin/vergo
cp dist/vergo_`uname | tr A-Z a-z`_amd64/vergo /usr/local/bin/vergo 2>/dev/null || true
   • building...      
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=fa0b98bc2f09dd4e499bf696d28b7fd926a6ebb5 latest tag=0+fa0b98b
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
   • running before hooks
      • running                   hook=go mod tidy
      • running                   hook=go mod download
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images    
      • docker manifests 
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • discord          
      • reddit           
      • slack            
      • teams            
      • twitter          
      • milestones       
   • snapshotting     
      • building snapshot...      version=0+fa0b98b
   • checking ./dist  
      • --rm-dist is set, cleaning it up
   • loading go mod information
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • pipe skipped              error=not available for snapshots
   • building binaries
      • building                  binary=/Users/dougala/workspace/vergo/dist/vergo_linux_arm64/vergo
      • building                  binary=/Users/dougala/workspace/vergo/dist/vergo_darwin_amd64/vergo
      • building                  binary=/Users/dougala/workspace/vergo/dist/vergo_darwin_arm64/vergo
      • building                  binary=/Users/dougala/workspace/vergo/dist/vergo_linux_amd64/vergo
   • build succeeded after 3.02s
This is a SNAPSHOT build
version: 0+fa0b98b
commit : fa0b98bc2f09dd4e499bf696d28b7fd926a6ebb5
date: 2023-02-08T14:58:45Z
builtBy: goreleaser version 0.179.0, go version go1.19.2 darwin/amd64
go clean -testcache
go test ./...
?       github.com/sky-uk/vergo [no test files]
ok      github.com/sky-uk/vergo/bump    0.470s
ok      github.com/sky-uk/vergo/cmd     0.682s
ok      github.com/sky-uk/vergo/git     0.803s
?       github.com/sky-uk/vergo/internal-test   [no test files]
ok      github.com/sky-uk/vergo/release 0.271s
./fun-tests/test.sh
./fun-tests/test-bump-auto.sh
./fun-tests/test-empty-repo.sh
+ export 'PS4=$0.$LINENO '
+ PS4='$0.$LINENO '
./fun-tests/test.sh.15 trap finish EXIT
./fun-tests/test.sh.16 trap 'exit 2' HUP INT QUIT TERM
../fun-tests/test.sh.40 git rev-parse HEAD
./fun-tests/test.sh.40 readonly head=fa0b98bc2f09dd4e499bf696d28b7fd926a6ebb5
./fun-tests/test.sh.40 head=fa0b98bc2f09dd4e499bf696d28b7fd926a6ebb5
../fun-tests/test.sh.41 git rev-parse --short HEAD
./fun-tests/test.sh.41 readonly headShort=fa0b98b
./fun-tests/test.sh.41 headShort=fa0b98b
../fun-tests/test.sh.42 vergo version simple
./fun-tests/test.sh.42 readonly 'vergoVersion=This is a SNAPSHOT build
0+fa0b98b'
./fun-tests/test.sh.42 vergoVersion='This is a SNAPSHOT build
0+fa0b98b'
./fun-tests/test.sh.43 setUp
./fun-tests/test.sh.20 cd /tmp
./fun-tests/test.sh.21 rm -rf /tmp/vergo-test-repo /tmp/vergo-test-repo-clone
./fun-tests/test.sh.22 git clone git@github.com:sky-uk/vergo-test-repo.git /tmp/vergo-test-repo
Cloning into '/tmp/vergo-test-repo'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (3/3), done.
remote: Total 23 (delta 3), reused 19 (delta 2), pack-reused 0
./fun-tests/test.sh.23 git clone /tmp/vergo-test-repo /tmp/vergo-test-repo-clone
Cloning into '/tmp/vergo-test-repo-clone'...
done.
./fun-tests/test.sh.24 cd /tmp/vergo-test-repo-clone
../fun-tests/test.sh.25 git tag -l apple-0.2.0 app-0.1.1 banana-2.0.0 orange/v3.0.0
./fun-tests/test.sh.25 [[ '' == '' ]]
./fun-tests/test.sh.46 vergo check release --tag-prefix=apple
./fun-tests/test.sh.47 vergo check release --tag-prefix=app
./fun-tests/test.sh.48 vergo check release --tag-prefix=banana
./fun-tests/test.sh.49 vergo check release --tag-prefix=cherry
Error: skip release hint present: cherry
./fun-tests/test.sh.52 true
../fun-tests/test.sh.54 vergo check release --tag-prefix=cherry
./fun-tests/test.sh.54 [[ Error: skip release hint present: cherry == \E\r\r\o\r\:\ \s\k\i\p\ \r\e\l\e\a\s\e\ \h\i\n\t\ \p\r\e\s\e\n\t\:\ \c\h\e\r\r\y ]]
../fun-tests/test.sh.57 vergo get lr --tag-prefix=apple
./fun-tests/test.sh.57 [[ 0.1.1 == \0\.\1\.\1 ]]
../fun-tests/test.sh.58 vergo get lr --tag-prefix=app
./fun-tests/test.sh.58 [[ 0.1.0 == \0\.\1\.\0 ]]
../fun-tests/test.sh.59 vergo get lr --tag-prefix=banana
./fun-tests/test.sh.59 [[ 1.1.2 == \1\.\1\.\2 ]]
../fun-tests/test.sh.60 vergo get lr --tag-prefix=orange/v
./fun-tests/test.sh.60 [[ 2.3.0 == \2\.\3\.\0 ]]
../fun-tests/test.sh.63 vergo get lr --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.63 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.1 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/apple-0.1.1}\n"
0.1.1 == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\0\.\1\.\1\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\a\p\p\l\e\-\0\.\1\.\1\}\\\n\"\
\0\.\1\.\1 ]]
../fun-tests/test.sh.65 vergo get lr --tag-prefix=app --log-level=trace
./fun-tests/test.sh.65 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/app-0.1.0}\n"
0.1.0 == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\0\.\1\.\0\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\a\p\p\-\0\.\1\.\0\}\\\n\"\
\0\.\1\.\0 ]]
../fun-tests/test.sh.67 vergo get lr --tag-prefix=orange/v --log-level=trace
./fun-tests/test.sh.67 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
2.3.0 == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\2\.\3\.\0\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\o\r\a\n\g\e\/\v\2\.\3\.\0\}\\\n\"\
\2\.\3\.\0 ]]
../fun-tests/test.sh.70 vergo get cv --tag-prefix=apple
./fun-tests/test.sh.70 [[ 0.2.0-SNAPSHOT == \0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.71 vergo get cv --tag-prefix=app
./fun-tests/test.sh.71 [[ 0.2.0-SNAPSHOT == \0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.72 vergo get cv --tag-prefix=orange/v
./fun-tests/test.sh.72 [[ 2.4.0-SNAPSHOT == \2\.\4\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.75 vergo get cv --tag-prefix=apple -p
./fun-tests/test.sh.75 [[ apple-0.2.0-SNAPSHOT == \a\p\p\l\e\-\0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.76 vergo get cv --tag-prefix=app -p
./fun-tests/test.sh.76 [[ app-0.2.0-SNAPSHOT == \a\p\p\-\0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.77 vergo get cv --tag-prefix=orange/v -p
./fun-tests/test.sh.77 [[ orange/v2.4.0-SNAPSHOT == \o\r\a\n\g\e\/\v\2\.\4\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.81 vergo get cv --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.81 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.1 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/apple-0.1.1}\n"
0.2.0-SNAPSHOT == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\0\.\1\.\1\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\a\p\p\l\e\-\0\.\1\.\1\}\\\n\"\
\0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.83 vergo get cv --tag-prefix=app --log-level=trace
./fun-tests/test.sh.83 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/app-0.1.0}\n"
0.2.0-SNAPSHOT == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\0\.\1\.\0\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\a\p\p\-\0\.\1\.\0\}\\\n\"\
\0\.\2\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.85 vergo get cv --tag-prefix=orange/v --log-level=trace
./fun-tests/test.sh.85 [[ time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
2.4.0-SNAPSHOT == *\l\e\v\e\l\=\d\e\b\u\g\ \m\s\g\=\"\L\a\t\e\s\t\ \v\e\r\s\i\o\n\:\ \{\2\.\3\.\0\ \b\2\6\9\5\4\d\9\c\b\2\0\e\5\8\b\5\d\6\d\9\b\9\c\1\9\3\0\a\e\9\9\8\e\8\b\6\e\3\c\ \r\e\f\s\/\t\a\g\s\/\o\r\a\n\g\e\/\v\2\.\3\.\0\}\\\n\"\
\2\.\4\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test.sh.88 vergo bump minor -tmelon --dry-run --log-level=error
./fun-tests/test.sh.88 [[ 0.1.0 == \0\.\1\.\0 ]]
../fun-tests/test.sh.91 vergo bump minor --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.91 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.1 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/apple-0.1.1}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag apple-0.2.0"
time="2023-02-08T14:58:54Z" level=trace msg="Push not enabled"
0.2.0 == *\S\e\t\ \t\a\g\ \a\p\p\l\e\-\0\.\2\.\0* ]]
../fun-tests/test.sh.92 vergo bump minor --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.92 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.2.0 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/apple-0.2.0}\n"
time="2023-02-08T14:58:54Z" level=trace msg="Push not enabled"
0.2.0 == *\P\u\s\h\ \n\o\t\ \e\n\a\b\l\e\d* ]]
../fun-tests/test.sh.93 vergo bump minor --tag-prefix=apple --log-level=error
./fun-tests/test.sh.93 [[ 0.2.0 == \0\.\2\.\0 ]]
../fun-tests/test.sh.95 vergo get lr --tag-prefix=apple
./fun-tests/test.sh.95 [[ 0.2.0 == \0\.\2\.\0 ]]
../fun-tests/test.sh.96 vergo get cv -tapple
./fun-tests/test.sh.96 [[ 0.2.0 == \0\.\2\.\0 ]]
../fun-tests/test.sh.99 vergo bump patch --tag-prefix=app --log-level=trace
./fun-tests/test.sh.99 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/app-0.1.0}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag app-0.1.1"
time="2023-02-08T14:58:54Z" level=trace msg="Push not enabled"
0.1.1 == *\S\e\t\ \t\a\g\ \a\p\p\-\0\.\1\.\1* ]]
../fun-tests/test.sh.100 vergo bump patch --tag-prefix=app --log-level=trace
./fun-tests/test.sh.100 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {0.1.1 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/app-0.1.1}\n"
time="2023-02-08T14:58:54Z" level=trace msg="Push not enabled"
0.1.1 == *\P\u\s\h\ \n\o\t\ \e\n\a\b\l\e\d* ]]
../fun-tests/test.sh.101 vergo bump patch --tag-prefix=app --log-level=error
./fun-tests/test.sh.101 [[ 0.1.1 == \0\.\1\.\1 ]]
../fun-tests/test.sh.103 vergo get lr -t=app
./fun-tests/test.sh.103 [[ 0.1.1 == \0\.\1\.\1 ]]
../fun-tests/test.sh.104 vergo get cv --tag-prefix=app
./fun-tests/test.sh.104 [[ 0.1.1 == \0\.\1\.\1 ]]
../fun-tests/test.sh.107 vergo bump major --push-tag --tag-prefix=banana --log-level=trace
./fun-tests/test.sh.107 readonly 'tagPrefixBananaVersion_2_0_0=time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {1.1.2 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/banana-1.1.2}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag banana-2.0.0"
time="2023-02-08T14:58:54Z" level=debug msg="Pushing tag: banana-2.0.0"
2.0.0'
./fun-tests/test.sh.107 tagPrefixBananaVersion_2_0_0='time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {1.1.2 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/banana-1.1.2}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag banana-2.0.0"
time="2023-02-08T14:58:54Z" level=debug msg="Pushing tag: banana-2.0.0"
2.0.0'
./fun-tests/test.sh.108 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {1.1.2 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/banana-1.1.2}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag banana-2.0.0"
time="2023-02-08T14:58:54Z" level=debug msg="Pushing tag: banana-2.0.0"
2.0.0 == *\S\e\t\ \t\a\g\ \b\a\n\a\n\a\-\2\.\0\.\0* ]]
./fun-tests/test.sh.109 [[ time="2023-02-08T14:58:54Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:54Z" level=debug msg="Latest version: {1.1.2 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/banana-1.1.2}\n"
time="2023-02-08T14:58:54Z" level=info msg="Set tag banana-2.0.0"
time="2023-02-08T14:58:54Z" level=debug msg="Pushing tag: banana-2.0.0"
2.0.0 == *\P\u\s\h\i\n\g\ \t\a\g\:\ \b\a\n\a\n\a\-\2\.\0\.\0* ]]
../fun-tests/test.sh.111 vergo get lr --tag-prefix=banana
./fun-tests/test.sh.111 [[ 2.0.0 == \2\.\0\.\0 ]]
../fun-tests/test.sh.112 vergo get cv --tag-prefix=banana
./fun-tests/test.sh.112 [[ 2.0.0 == \2\.\0\.\0 ]]
../fun-tests/test.sh.115 vergo bump minor --push-tag --tag-prefix=mango --log-level=trace -d
./fun-tests/test.sh.115 readonly 'tagPrefixBananaVersion_3_0_0=time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=info msg="Set tag mango-0.1.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: mango-0.1.0"
0.1.0'
./fun-tests/test.sh.115 tagPrefixBananaVersion_3_0_0='time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=info msg="Set tag mango-0.1.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: mango-0.1.0"
0.1.0'
./fun-tests/test.sh.116 [[ time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=info msg="Set tag mango-0.1.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: mango-0.1.0"
0.1.0 == *\S\e\t\ \t\a\g\ \m\a\n\g\o\-\0\.\1\.\0* ]]
./fun-tests/test.sh.117 [[ time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=info msg="Set tag mango-0.1.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: mango-0.1.0"
0.1.0 == *\P\u\s\h\i\n\g\ \t\a\g\:\ \m\a\n\g\o\-\0\.\1\.\0* ]]
../fun-tests/test.sh.119 vergo get lr --tag-prefix=mango
./fun-tests/test.sh.119 [[ 0.1.0 == \0\.\1\.\0 ]]
../fun-tests/test.sh.120 vergo get cv --tag-prefix=mango
./fun-tests/test.sh.120 [[ 0.1.0 == \0\.\1\.\0 ]]
../fun-tests/test.sh.123 vergo bump major --push-tag --tag-prefix=orange/v --log-level=trace
./fun-tests/test.sh.123 readonly 'tagPrefixOrangeVersion_3_0_0=time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
time="2023-02-08T14:58:55Z" level=info msg="Set tag orange/v3.0.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: orange/v3.0.0"
3.0.0'
./fun-tests/test.sh.123 tagPrefixOrangeVersion_3_0_0='time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
time="2023-02-08T14:58:55Z" level=info msg="Set tag orange/v3.0.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: orange/v3.0.0"
3.0.0'
./fun-tests/test.sh.124 [[ time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
time="2023-02-08T14:58:55Z" level=info msg="Set tag orange/v3.0.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: orange/v3.0.0"
3.0.0 == *\S\e\t\ \t\a\g\ \o\r\a\n\g\e\/\v\3\.\0\.\0* ]]
./fun-tests/test.sh.125 [[ time="2023-02-08T14:58:55Z" level=debug msg="Current branch:refs/heads/master, short: master"
time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {2.3.0 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/orange/v2.3.0}\n"
time="2023-02-08T14:58:55Z" level=info msg="Set tag orange/v3.0.0"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: orange/v3.0.0"
3.0.0 == *\P\u\s\h\i\n\g\ \t\a\g\:\ \o\r\a\n\g\e\/\v\3\.\0\.\0* ]]
../fun-tests/test.sh.127 vergo get lr --tag-prefix=orange/v
./fun-tests/test.sh.127 [[ 3.0.0 == \3\.\0\.\0 ]]
../fun-tests/test.sh.128 vergo get cv --tag-prefix=orange/v
./fun-tests/test.sh.128 [[ 3.0.0 == \3\.\0\.\0 ]]
../fun-tests/test.sh.132 vergo list --tag-prefix=app --log-level=trace
./fun-tests/test.sh.132 [[ 0.1.1
0.1.0 == *\0\.\1\.\1\
\0\.\1\.\0 ]]
../fun-tests/test.sh.134 vergo list --tag-prefix=app --log-level=trace --sort-direction asc
./fun-tests/test.sh.134 [[ 0.1.0
0.1.1 == *\0\.\1\.\0\
\0\.\1\.\1 ]]
../fun-tests/test.sh.137 vergo list --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.137 [[ 0.2.0
0.1.1 == *\0\.\2\.\0\
\0\.\1\.\1 ]]
../fun-tests/test.sh.139 vergo list --tag-prefix=apple --log-level=trace --sort-direction asc
./fun-tests/test.sh.139 [[ 0.1.1
0.2.0 == *\0\.\1\.\1\
\0\.\2\.\0 ]]
../fun-tests/test.sh.143 vergo list --tag-prefix=orange/v --log-level=trace
./fun-tests/test.sh.143 [[ 3.0.0
2.3.0 == *\3\.\0\.\0\
\2\.\3\.\0 ]]
../fun-tests/test.sh.145 vergo list --tag-prefix=orange/v --log-level=trace --sort-direction asc
./fun-tests/test.sh.145 [[ 2.3.0
3.0.0 == *\2\.\3\.\0\
\3\.\0\.\0 ]]
../fun-tests/test.sh.149 vergo list --tag-prefix=app -p --log-level=trace
./fun-tests/test.sh.149 [[ app-0.1.1
app-0.1.0 == *\a\p\p\-\0\.\1\.\1\
\a\p\p\-\0\.\1\.\0 ]]
../fun-tests/test.sh.151 vergo list --tag-prefix=app -p --log-level=trace --sort-direction asc
./fun-tests/test.sh.151 [[ app-0.1.0
app-0.1.1 == *\a\p\p\-\0\.\1\.\0\
\a\p\p\-\0\.\1\.\1 ]]
../fun-tests/test.sh.155 vergo list --tag-prefix=apple -p --log-level=trace
./fun-tests/test.sh.155 [[ apple-0.2.0
apple-0.1.1 == *\a\p\p\l\e\-\0\.\2\.\0\
\a\p\p\l\e\-\0\.\1\.\1 ]]
../fun-tests/test.sh.157 vergo list --tag-prefix=apple -p --log-level=trace --sort-direction asc
./fun-tests/test.sh.157 [[ apple-0.1.1
apple-0.2.0 == *\a\p\p\l\e\-\0\.\1\.\1\
\a\p\p\l\e\-\0\.\2\.\0 ]]
../fun-tests/test.sh.160 vergo push --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.160 [[ time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {0.2.0 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/apple-0.2.0}\n"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: apple-0.2.0" == *\P\u\s\h\i\n\g\ \t\a\g\:\ \a\p\p\l\e\-\0\.\2\.\0* ]]
../fun-tests/test.sh.161 vergo push --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.161 [[ time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {0.2.0 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/apple-0.2.0}\n"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: apple-0.2.0"
time="2023-02-08T14:58:55Z" level=info msg="origin remote was up to date, no push done" == *\P\u\s\h\i\n\g\ \t\a\g\:\ \a\p\p\l\e\-\0\.\2\.\0* ]]
../fun-tests/test.sh.162 vergo push --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.162 [[ time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {0.2.0 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/apple-0.2.0}\n"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: apple-0.2.0"
time="2023-02-08T14:58:55Z" level=info msg="origin remote was up to date, no push done" == *\o\r\i\g\i\n\ \r\e\m\o\t\e\ \w\a\s\ \u\p\ \t\o\ \d\a\t\e\,\ \n\o\ \p\u\s\h\ \d\o\n\e* ]]
../fun-tests/test.sh.163 vergo push --tag-prefix=app --log-level=trace
./fun-tests/test.sh.163 [[ time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {0.1.1 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/app-0.1.1}\n"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: app-0.1.1" == *\P\u\s\h\i\n\g\ \t\a\g\:\ \a\p\p\-\0\.\1\.\1* ]]
../fun-tests/test.sh.164 vergo push --tag-prefix=orange/v --log-level=trace
./fun-tests/test.sh.164 [[ time="2023-02-08T14:58:55Z" level=debug msg="Latest version: {3.0.0 a54f1f7d545ea0e6b6a58f0f51285d6ca0722590 refs/tags/orange/v3.0.0}\n"
time="2023-02-08T14:58:55Z" level=debug msg="Pushing tag: orange/v3.0.0"
time="2023-02-08T14:58:55Z" level=info msg="origin remote was up to date, no push done" == *\P\u\s\h\i\n\g\ \t\a\g\:\ \o\r\a\n\g\e\/\v\3\.\0\.\0* ]]
../fun-tests/test.sh.167 git ls-remote --tags origin apple-0.2.0 app-0.1.1 banana-2.0.0 orange/v3.0.0
./fun-tests/test.sh.167 remote_tags='a54f1f7d545ea0e6b6a58f0f51285d6ca0722590   refs/tags/app-0.1.1
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/apple-0.2.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/banana-2.0.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/orange/v3.0.0'
./fun-tests/test.sh.168 [[ a54f1f7d545ea0e6b6a58f0f51285d6ca0722590     refs/tags/app-0.1.1
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/apple-0.2.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/banana-2.0.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/orange/v3.0.0 == *\r\e\f\s\/\t\a\g\s\/\a\p\p\-\0\.\1\.\1* ]]
./fun-tests/test.sh.169 [[ a54f1f7d545ea0e6b6a58f0f51285d6ca0722590     refs/tags/app-0.1.1
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/apple-0.2.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/banana-2.0.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/orange/v3.0.0 == *\r\e\f\s\/\t\a\g\s\/\a\p\p\l\e\-\0\.\2\.\0* ]]
./fun-tests/test.sh.170 [[ a54f1f7d545ea0e6b6a58f0f51285d6ca0722590     refs/tags/app-0.1.1
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/apple-0.2.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/banana-2.0.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/orange/v3.0.0 == *\r\e\f\s\/\t\a\g\s\/\b\a\n\a\n\a\-\2\.\0\.\0* ]]
./fun-tests/test.sh.171 [[ a54f1f7d545ea0e6b6a58f0f51285d6ca0722590     refs/tags/app-0.1.1
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/apple-0.2.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/banana-2.0.0
a54f1f7d545ea0e6b6a58f0f51285d6ca0722590        refs/tags/orange/v3.0.0 == *\r\e\f\s\/\t\a\g\s\/\o\r\a\n\g\e\/\v\3\.\0\.\0* ]]
./fun-tests/test.sh.174 setUpLikeCI
./fun-tests/test.sh.29 cd /tmp
./fun-tests/test.sh.30 rm -rf /tmp/vergo-test-repo /tmp/vergo-test-repo-clone
./fun-tests/test.sh.31 git init /tmp/vergo-test-repo
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /private/tmp/vergo-test-repo/.git/
./fun-tests/test.sh.32 git -C /tmp/vergo-test-repo fetch --tags -- git@github.com:sky-uk/vergo-test-repo.git '+refs/heads/*:refs/remotes/origin/*'
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 23 (delta 3), reused 19 (delta 2), pack-reused 0
Unpacking objects: 100% (23/23), 2.48 KiB | 76.00 KiB/s, done.
From github.com:sky-uk/vergo-test-repo
 * [new branch]      master        -> origin/master
 * [new branch]      test-branch   -> origin/test-branch
 * [new tag]         app-0.1.0     -> app-0.1.0
 * [new tag]         apple-0.1.1   -> apple-0.1.1
 * [new tag]         banana-1.1.2  -> banana-1.1.2
 * [new tag]         orange/v2.3.0 -> orange/v2.3.0
../fun-tests/test.sh.33 git -C /tmp/vergo-test-repo show-ref --hash refs/remotes/origin/master
./fun-tests/test.sh.33 git -C /tmp/vergo-test-repo checkout a54f1f7d545ea0e6b6a58f0f51285d6ca0722590
Note: switching to 'a54f1f7d545ea0e6b6a58f0f51285d6ca0722590'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a54f1f7 [vergo:cherry:skip-release] add README.md
./fun-tests/test.sh.34 git -C /tmp/vergo-test-repo config remote.origin.url git@github.com:sky-uk/vergo-test-repo.git
./fun-tests/test.sh.36 cd /tmp/vergo-test-repo
../fun-tests/test.sh.37 git tag -l apple-0.2.0 app-0.1.1 banana-2.0.0 orange/v3.0.0
./fun-tests/test.sh.37 [[ '' == '' ]]
../fun-tests/test.sh.176 git branch -l
../fun-tests/test.sh.176 grep -v HEAD
./fun-tests/test.sh.176 [[ '' == '' ]]
./fun-tests/test.sh.177 git checkout d13ae40
Previous HEAD position was a54f1f7 [vergo:cherry:skip-release] add README.md
HEAD is now at d13ae40 Some test file to be used for testing headless checkout
../fun-tests/test.sh.178 vergo check release --tag-prefix=apple
./fun-tests/test.sh.178 [[ time="2023-02-08T14:58:57Z" level=warning msg="Commit not found on branch [branch: refs/remotes/origin/master, head: d13ae404111bfcdae0db69412cb38ecf1e1cc3ad, ref: a54f1f7d545ea0e6b6a58f0f51285d6ca0722590]\n"
Error: HEAD validation: invalid headless checkout == *\i\n\v\a\l\i\d\ \h\e\a\d\l\e\s\s\ \c\h\e\c\k\o\u\t* ]]
../fun-tests/test.sh.179 vergo bump minor --tag-prefix=apple
./fun-tests/test.sh.179 [[ time="2023-02-08T14:58:57Z" level=warning msg="Commit not found on branch [branch: refs/remotes/origin/master, head: d13ae404111bfcdae0db69412cb38ecf1e1cc3ad, ref: a54f1f7d545ea0e6b6a58f0f51285d6ca0722590]\n"
Error: HEAD validation: invalid headless checkout == *\i\n\v\a\l\i\d\ \h\e\a\d\l\e\s\s\ \c\h\e\c\k\o\u\t* ]]
../fun-tests/test.sh.181 git branch -l
../fun-tests/test.sh.181 grep -v HEAD
./fun-tests/test.sh.181 [[ '' == '' ]]
./fun-tests/test.sh.182 git checkout a54f1f7
Previous HEAD position was d13ae40 Some test file to be used for testing headless checkout
HEAD is now at a54f1f7 [vergo:cherry:skip-release] add README.md
./fun-tests/test.sh.183 vergo check release --tag-prefix=apple
../fun-tests/test.sh.184 vergo bump minor --tag-prefix=apple --log-level=trace
./fun-tests/test.sh.184 [[ time="2023-02-08T14:58:58Z" level=debug msg="Current branch:HEAD, short: HEAD"
time="2023-02-08T14:58:58Z" level=debug msg="Latest version: {0.1.1 b26954d9cb20e58b5d6d9b9c1930ae998e8b6e3c refs/tags/apple-0.1.1}\n"
time="2023-02-08T14:58:58Z" level=info msg="Set tag apple-0.2.0"
time="2023-02-08T14:58:58Z" level=trace msg="Push not enabled"
0.2.0 == *\S\e\t\ \t\a\g\ \a\p\p\l\e\-\0\.\2\.\0* ]]
./fun-tests/test.sh.186 git checkout origin/master -b master
Switched to a new branch 'master'
../fun-tests/test.sh.187 vergo check release --tag-prefix=apple --log-level=trace --versioned-branch-names main
./fun-tests/test.sh.187 [[ time="2023-02-08T14:58:58Z" level=debug msg="Current branch:refs/heads/master, short: master"
Error: HEAD validation: branch master is not in main branches list: main == *\b\r\a\n\c\h\ \m\a\s\t\e\r\ \i\s\ \n\o\t\ \i\n\ \m\a\i\n\ \b\r\a\n\c\h\e\s\ \l\i\s\t\:\ \m\a\i\n* ]]
../fun-tests/test.sh.188 vergo bump minor --tag-prefix=apple --log-level=trace --versioned-branch-names main
./fun-tests/test.sh.188 [[ time="2023-02-08T14:58:58Z" level=debug msg="Current branch:refs/heads/master, short: master"
Error: HEAD validation: branch master is not in main branches list: main == *\b\r\a\n\c\h\ \m\a\s\t\e\r\ \i\s\ \n\o\t\ \i\n\ \m\a\i\n\ \b\r\a\n\c\h\e\s\ \l\i\s\t\:\ \m\a\i\n* ]]
./fun-tests/test.sh.1 finish
./fun-tests/test.sh.7 local rc=0
./fun-tests/test.sh.8 (( rc == 0 ))
./fun-tests/test.sh.9 echo OK
OK
./fun-tests/test.sh.13 exit 0
+ export 'PS4=$0.$LINENO '
+ PS4='$0.$LINENO '
./fun-tests/test-bump-auto.sh.15 trap finish EXIT
./fun-tests/test-bump-auto.sh.16 trap 'exit 2' HUP INT QUIT TERM
../fun-tests/test-bump-auto.sh.88 compgen -A function
../fun-tests/test-bump-auto.sh.88 grep -E '^Test'
./fun-tests/test-bump-auto.sh.88 tests='TestAutoApplePrefix
TestAutoEmptyPrefix
TestAutoEmptyRepo
TestAutoNotMatchingCommitMessage
TestCheckIncrementWithSkipReleaseHint'
./fun-tests/test-bump-auto.sh.89 for fn in $tests
./fun-tests/test-bump-auto.sh.90 TestAutoApplePrefix
./fun-tests/test-bump-auto.sh.57 setup
../fun-tests/test-bump-auto.sh.19 mktemp -d
./fun-tests/test-bump-auto.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1
./fun-tests/test-bump-auto.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1
./fun-tests/test-bump-auto.sh.21 git init -q
./fun-tests/test-bump-auto.sh.22 git config user.email vergo@example.com
./fun-tests/test-bump-auto.sh.23 git config user.name vergo
./fun-tests/test-bump-auto.sh.58 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1/Ck0Ii
./fun-tests/test-bump-auto.sh.59 git add .
./fun-tests/test-bump-auto.sh.59 git commit '-am[vergo:apple:major-release] a commit'
[master (root-commit) 8d7289e] [vergo:apple:major-release] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 Ck0Ii
../fun-tests/test-bump-auto.sh.61 vergo bump auto
./fun-tests/test-bump-auto.sh.61 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
../fun-tests/test-bump-auto.sh.62 vergo bump auto --tag-prefix=apple
./fun-tests/test-bump-auto.sh.62 [[ time="2023-02-08T14:58:58Z" level=info msg="Set tag apple-0.1.0"
0.1.0 == *\0\.\1\.\0* ]]
../fun-tests/test-bump-auto.sh.63 vergo check increment-hint
./fun-tests/test-bump-auto.sh.63 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
./fun-tests/test-bump-auto.sh.64 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.66 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.SULjvUn1/qD378
./fun-tests/test-bump-auto.sh.67 git add .
./fun-tests/test-bump-auto.sh.67 git commit '-am[vergo:apple:major-release] a commit'
[master 6d47066] [vergo:apple:major-release] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 qD378
../fun-tests/test-bump-auto.sh.69 vergo bump auto
./fun-tests/test-bump-auto.sh.69 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
../fun-tests/test-bump-auto.sh.70 vergo bump auto --tag-prefix=apple
./fun-tests/test-bump-auto.sh.70 [[ time="2023-02-08T14:58:58Z" level=info msg="Set tag apple-1.0.0"
1.0.0 == *\1\.\0\.\0* ]]
../fun-tests/test-bump-auto.sh.71 vergo check increment-hint
./fun-tests/test-bump-auto.sh.71 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
./fun-tests/test-bump-auto.sh.72 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.89 for fn in $tests
./fun-tests/test-bump-auto.sh.90 TestAutoEmptyPrefix
./fun-tests/test-bump-auto.sh.46 setup
../fun-tests/test-bump-auto.sh.19 mktemp -d
./fun-tests/test-bump-auto.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.LQuJFZYW
./fun-tests/test-bump-auto.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.LQuJFZYW
./fun-tests/test-bump-auto.sh.21 git init -q
./fun-tests/test-bump-auto.sh.22 git config user.email vergo@example.com
./fun-tests/test-bump-auto.sh.23 git config user.name vergo
./fun-tests/test-bump-auto.sh.47 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.LQuJFZYW/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.LQuJFZYW/GpBKI
./fun-tests/test-bump-auto.sh.48 git add .
./fun-tests/test-bump-auto.sh.48 git commit '-am[vergo:minor-release] a commit'
[master (root-commit) 4e724ab] [vergo:minor-release] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 GpBKI
../fun-tests/test-bump-auto.sh.50 vergo bump auto
./fun-tests/test-bump-auto.sh.50 [[ time="2023-02-08T14:58:58Z" level=info msg="Set tag v0.1.0"
0.1.0 == *\0\.\1\.\0* ]]
../fun-tests/test-bump-auto.sh.51 vergo bump auto --tag-prefix=apple
./fun-tests/test-bump-auto.sh.51 [[ Error: increment hint not present: apple == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t\:\ \a\p\p\l\e* ]]
./fun-tests/test-bump-auto.sh.52 vergo check increment-hint
../fun-tests/test-bump-auto.sh.53 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.53 [[ Error: increment hint not present: apple == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t\:\ \a\p\p\l\e* ]]
./fun-tests/test-bump-auto.sh.89 for fn in $tests
./fun-tests/test-bump-auto.sh.90 TestAutoEmptyRepo
./fun-tests/test-bump-auto.sh.27 setup
../fun-tests/test-bump-auto.sh.19 mktemp -d
./fun-tests/test-bump-auto.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.s5zlBzTZ
./fun-tests/test-bump-auto.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.s5zlBzTZ
./fun-tests/test-bump-auto.sh.21 git init -q
./fun-tests/test-bump-auto.sh.22 git config user.email vergo@example.com
./fun-tests/test-bump-auto.sh.23 git config user.name vergo
../fun-tests/test-bump-auto.sh.28 vergo bump auto
./fun-tests/test-bump-auto.sh.28 [[ Error: reference not found == *\E\r\r\o\r\:\ \r\e\f\e\r\e\n\c\e\ \n\o\t\ \f\o\u\n\d* ]]
../fun-tests/test-bump-auto.sh.29 vergo bump auto --tag-prefix=apple
./fun-tests/test-bump-auto.sh.29 [[ Error: reference not found == *\E\r\r\o\r\:\ \r\e\f\e\r\e\n\c\e\ \n\o\t\ \f\o\u\n\d* ]]
./fun-tests/test-bump-auto.sh.30 vergo check increment-hint
./fun-tests/test-bump-auto.sh.31 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.89 for fn in $tests
./fun-tests/test-bump-auto.sh.90 TestAutoNotMatchingCommitMessage
./fun-tests/test-bump-auto.sh.35 setup
../fun-tests/test-bump-auto.sh.19 mktemp -d
./fun-tests/test-bump-auto.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.qIqowhIO
./fun-tests/test-bump-auto.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.qIqowhIO
./fun-tests/test-bump-auto.sh.21 git init -q
./fun-tests/test-bump-auto.sh.22 git config user.email vergo@example.com
./fun-tests/test-bump-auto.sh.23 git config user.name vergo
./fun-tests/test-bump-auto.sh.36 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.qIqowhIO/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.qIqowhIO/hGouO
./fun-tests/test-bump-auto.sh.37 git add .
./fun-tests/test-bump-auto.sh.37 git commit '-ama commit'
[master (root-commit) 2e73d78] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 hGouO
../fun-tests/test-bump-auto.sh.39 vergo bump auto
./fun-tests/test-bump-auto.sh.39 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
../fun-tests/test-bump-auto.sh.40 vergo bump auto --tag-prefix=apple
./fun-tests/test-bump-auto.sh.40 [[ Error: increment hint not present: apple == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t\:\ \a\p\p\l\e* ]]
../fun-tests/test-bump-auto.sh.41 vergo check increment-hint
./fun-tests/test-bump-auto.sh.41 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
../fun-tests/test-bump-auto.sh.42 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.42 [[ Error: increment hint not present: apple == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t\:\ \a\p\p\l\e* ]]
./fun-tests/test-bump-auto.sh.89 for fn in $tests
./fun-tests/test-bump-auto.sh.90 TestCheckIncrementWithSkipReleaseHint
./fun-tests/test-bump-auto.sh.76 setup
../fun-tests/test-bump-auto.sh.19 mktemp -d
./fun-tests/test-bump-auto.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG
./fun-tests/test-bump-auto.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG
./fun-tests/test-bump-auto.sh.21 git init -q
./fun-tests/test-bump-auto.sh.22 git config user.email vergo@example.com
./fun-tests/test-bump-auto.sh.23 git config user.name vergo
./fun-tests/test-bump-auto.sh.77 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG/RHrgb
./fun-tests/test-bump-auto.sh.78 git add .
./fun-tests/test-bump-auto.sh.78 git commit '-am[vergo:skip-release] a commit'
[master (root-commit) 54fda19] [vergo:skip-release] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 RHrgb
./fun-tests/test-bump-auto.sh.79 vergo check increment-hint
../fun-tests/test-bump-auto.sh.80 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.80 [[ Error: increment hint not present: apple == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t\:\ \a\p\p\l\e* ]]
./fun-tests/test-bump-auto.sh.82 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.fKU2YoDG/HhqPl
./fun-tests/test-bump-auto.sh.83 git add .
./fun-tests/test-bump-auto.sh.83 git commit '-am[vergo:apple:skip-release] a commit'
[master 4a97473] [vergo:apple:skip-release] a commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 HhqPl
../fun-tests/test-bump-auto.sh.84 vergo check increment-hint
./fun-tests/test-bump-auto.sh.84 [[ Error: increment hint not present:  == *\E\r\r\o\r\:\ \i\n\c\r\e\m\e\n\t\ \h\i\n\t\ \n\o\t\ \p\r\e\s\e\n\t* ]]
./fun-tests/test-bump-auto.sh.85 vergo check increment-hint --tag-prefix=apple
./fun-tests/test-bump-auto.sh.1 finish
./fun-tests/test-bump-auto.sh.7 local rc=0
./fun-tests/test-bump-auto.sh.8 (( rc == 0 ))
./fun-tests/test-bump-auto.sh.9 echo OK
OK
./fun-tests/test-bump-auto.sh.13 exit 0
+ export 'PS4=$0.$LINENO '
+ PS4='$0.$LINENO '
./fun-tests/test-empty-repo.sh.15 trap finish EXIT
./fun-tests/test-empty-repo.sh.16 trap 'exit 2' HUP INT QUIT TERM
../fun-tests/test-empty-repo.sh.46 compgen -A function
../fun-tests/test-empty-repo.sh.46 grep -E '^Test'
./fun-tests/test-empty-repo.sh.46 tests='TestCurrentVersionEmptyRepo
TestCurrentVersionNoTags'
./fun-tests/test-empty-repo.sh.47 for fn in $tests
./fun-tests/test-empty-repo.sh.48 TestCurrentVersionEmptyRepo
./fun-tests/test-empty-repo.sh.27 setup
../fun-tests/test-empty-repo.sh.19 mktemp -d
./fun-tests/test-empty-repo.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.1Vai4QZ0
./fun-tests/test-empty-repo.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.1Vai4QZ0
./fun-tests/test-empty-repo.sh.21 git init -q
./fun-tests/test-empty-repo.sh.22 git config user.email vergo@example.com
./fun-tests/test-empty-repo.sh.23 git config user.name vergo
../fun-tests/test-empty-repo.sh.28 vergo get cv
./fun-tests/test-empty-repo.sh.28 [[ 0.0.0-SNAPSHOT == \0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.29 vergo get cv -p
./fun-tests/test-empty-repo.sh.29 [[ v0.0.0-SNAPSHOT == \v\0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.30 vergo get cv -t apple
./fun-tests/test-empty-repo.sh.30 [[ 0.0.0-SNAPSHOT == \0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.31 vergo get cv -t apple -p
./fun-tests/test-empty-repo.sh.31 [[ apple-0.0.0-SNAPSHOT == \a\p\p\l\e\-\0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.32 vergo bump minor
./fun-tests/test-empty-repo.sh.32 [[ Error: reference not found == \E\r\r\o\r\:\ \r\e\f\e\r\e\n\c\e\ \n\o\t\ \f\o\u\n\d ]]
../fun-tests/test-empty-repo.sh.33 vergo bump auto
./fun-tests/test-empty-repo.sh.33 [[ Error: reference not found == \E\r\r\o\r\:\ \r\e\f\e\r\e\n\c\e\ \n\o\t\ \f\o\u\n\d ]]
./fun-tests/test-empty-repo.sh.47 for fn in $tests
./fun-tests/test-empty-repo.sh.48 TestCurrentVersionNoTags
./fun-tests/test-empty-repo.sh.37 setup
../fun-tests/test-empty-repo.sh.19 mktemp -d
./fun-tests/test-empty-repo.sh.19 some_temp_folder=/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.Jot1CyN8
./fun-tests/test-empty-repo.sh.20 cd /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.Jot1CyN8
./fun-tests/test-empty-repo.sh.21 git init -q
./fun-tests/test-empty-repo.sh.22 git config user.email vergo@example.com
./fun-tests/test-empty-repo.sh.23 git config user.name vergo
./fun-tests/test-empty-repo.sh.38 mktemp /var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.Jot1CyN8/XXXXX
/var/folders/23/vw68lsd159vfqwwzc48tlp2c0000gp/T/tmp.Jot1CyN8/lJjEp
./fun-tests/test-empty-repo.sh.39 git add .
./fun-tests/test-empty-repo.sh.39 git commit '-amfirst commit'
[master (root-commit) 7a873a4] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 lJjEp
../fun-tests/test-empty-repo.sh.40 vergo get cv
./fun-tests/test-empty-repo.sh.40 [[ 0.0.0-SNAPSHOT == \0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.41 vergo get cv -p
./fun-tests/test-empty-repo.sh.41 [[ v0.0.0-SNAPSHOT == \v\0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.42 vergo get cv -t apple
./fun-tests/test-empty-repo.sh.42 [[ 0.0.0-SNAPSHOT == \0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
../fun-tests/test-empty-repo.sh.43 vergo get cv -t apple -p
./fun-tests/test-empty-repo.sh.43 [[ apple-0.0.0-SNAPSHOT == \a\p\p\l\e\-\0\.\0\.\0\-\S\N\A\P\S\H\O\T ]]
./fun-tests/test-empty-repo.sh.1 finish
./fun-tests/test-empty-repo.sh.7 local rc=0
./fun-tests/test-empty-repo.sh.8 (( rc == 0 ))
./fun-tests/test-empty-repo.sh.9 echo OK
OK
./fun-tests/test-empty-repo.sh.13 exit 0
```

File: release/release.go [hunk 1]
```diff
@@ -142,3 +148,39 @@ func PreRelease(repo *gogit.Repository, options PreReleaseOptions) PreReleaseFun
...
+		return true, nil
+	}
+
+	branchCommitObject, err := repo.CommitObject(branchCommit)
+	if err != nil {
+		return false, err
+	}
+
+	for _, parentHash := range branchCommitObject.ParentHashes {
+		reaches, err := reaches(repo, parentHash, commitToFind)
```
Comment (aecay) [inline release/release.go:177]: this recursive call will blow the stack.  i think you need a loop of some sort.

**Comment by chuckydev** [comment]
Would you mind following the commit naming for https://github.com/sky-uk/vergo/blob/master/CONTRIBUTING.md#releasing?

File: release/release.go (hunk 1 above)
Comment (adamdougal) [reply release/release.go:177]: I'm not sure how you'd get this to work with just a loop. `go-git` doesn't have a feature to loop through commits in a branch. I'm also not sure it'd be possible to convert this to tail recursion, but I've only briefly looked.

FWIW I ran this against a branch off of `core-platform` which has ~16,000 commits with no issues and it returned almost immediately.

Comment (adamdougal) [reply release/release.go:177]: Actually I'm not sure my manual test against core-platform was correct. Re-running you can see it taking a long time.

Comment (aecay) [reply release/release.go:177]: > FWIW I ran this against a branch off of core-platform which has ~16,000 commits with no issues and it returned almost immediately.

Did you run it with a non-reachable commit ID?  That's when the stack will blow (because it has to check all 16,000 commits on the branch before it can be satisfied that the commit is not reachable, and each commit pushes a new stack frame)

> I'm also not sure it'd be possible to convert this to tail recursion

No(t easily) -- also the go language doesn't mandate support for optimized tail recursion so even that wouldn't help.

> go-git doesn't have a feature to loop through commits in a branch

No, you have to do it yourself.  The "dumb way" is with a deque of commits where you do:

```
while commit := deque.Pop() {
    if commit == commitToSearchFor {
        return found
    }
   deque.Push(commit.Parents())
}
```

You can optimize this by staying out of the data structure when you are looking at linear history:

```
commitsToCheck := deque.New(initialCommit)
while commit := commitsToCheck.Pop() {
    while len(commit.Parents()) == 1 {
        if commit == commitToFind { return found }
        commit = commit.Parents()[0]
    }
    if commit == commitToFind { return found }
    commitsToCheck.Push(commit.Parents()...)
}
```

(also you probably want to figure out how to do it without a deque but using only slices, which probably can be used as a shitty deque anyway since allocation isn't a major concern as long as you apply the optimization for linear history)

Comment (adamdougal) [reply release/release.go:177]: Whats frustrating, is that this is built into `git` cli. We could use that and it'd be as simple as:
```golang
func isCommitOnBranch(repo *gogit.Repository, commit plumbing.Hash, branch string) (bool, error) {
	cmd := exec.Command("bash", "-c", "git branch -r --contains ", commit.String())

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()

	if err != nil {
		return false, errors.New("unable to check if git commit exists for branch:\n " + stderr.String())
	}

	branchesForCommit := strings.Split(stdout.String(), "\n")
	return contains(branchesForCommit, "origin/"+branch), nil
}
```

But I'm hesitant to go down that route given we already use `go-git`.

Comment (adamdougal) [reply release/release.go:177]: If I introduce the memoization that was on the linked example, it runs much faster (~2s). 

```bash
16:36:25 [~/workspace/core-platform] {130}:git st
HEAD detached at c79eec274
nothing to commit, working tree clean
16:36:26 [~/workspace/core-platform] {0}:../vergo/bin/vergo-memorized check release --log-level=debug
DEBU[0000] Current branch:HEAD, short: HEAD
WARN[0001] Commit not found on branch [branch: refs/remotes/origin/master, head: c79eec2743671696d836e4d4de2e0e0709a96056, ref: 680ea2fc80029e4dcea251b0a91b27207d9599aa]
DEBU[0001] branchRef could not be resolved: refs/remotes/origin/main  error="reference not found"
Error: HEAD validation: invalid headless checkout
16:36:31 [~/workspace/core-platform] {1}:
```

With `c79eec274` being a revision of a commit on a branch of the `core-platform` repo. 

I'll push that up now.

It's also worth mentioning that this shouldn't happen often. Only if a team has misconfigured a cd script. Usually tenants will check they're on master/main before calling vergo.

Comment (adamdougal) [reply release/release.go]: @aecay Does that alleviate your concerns? If not we'll have to get this bug prioritised within our sprints to dedicate more time to it. At the moment I've been squeezing this in and around meetings etc.

Comment (aecay) [reply release/release.go]: yes, the new change lgtm.  thanks! 🙂

**Review by aecay — APPROVED** [review]
